<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\AnalyticsSnapshot;
use App\Models\Post;
use App\Models\Workspace;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log;

class InsightService
{
    public function __construct(
        private readonly AIService $aiService,
    ) {}

    /**
     * Get daily insights for a workspace.
     * Returns cached insights from workspace settings, or generates placeholder if stale/missing.
     */
    public function getDailyInsights(int $workspaceId): array
    {
        $workspace = Workspace::find($workspaceId);

        if (! $workspace) {
            return $this->getPlaceholderInsights();
        }

        $settings = $workspace->settings ?? [];
        $cachedInsights = $settings['daily_insights'] ?? null;
        $cachedAt = $settings['daily_insights_at'] ?? null;

        // If we have cached insights that are less than 24 hours old, use them
        if ($cachedInsights && $cachedAt) {
            $cachedTime = Carbon::parse($cachedAt);
            if ($cachedTime->diffInHours(now()) < 24) {
                return $cachedInsights;
            }
        }

        // Return placeholder insights (real ones will be generated by GenerateDailyInsightsJob)
        return $this->getPlaceholderInsights();
    }

    /**
     * Generate fresh insights using AI and cache them.
     */
    public function generateAndCacheInsights(int $workspaceId): array
    {
        $workspace = Workspace::find($workspaceId);
        if (! $workspace) {
            return [];
        }

        try {
            $contextData = $this->gatherInsightContext($workspaceId);
            $prompt = $this->buildInsightPrompt($contextData);

            $response = $this->aiService->complete(
                feature: 'insight',
                userPrompt: $prompt,
                systemPrompt: $this->getSystemPrompt(),
                workspaceId: $workspaceId,
            );

            $insights = $this->parseInsightResponse($response);

            // Cache in workspace settings
            $settings = $workspace->settings ?? [];
            $settings['daily_insights'] = $insights;
            $settings['daily_insights_at'] = now()->toISOString();
            $workspace->update(['settings' => $settings]);

            return $insights;
        } catch (\Exception $e) {
            Log::warning('Failed to generate AI insights', [
                'workspace_id' => $workspaceId,
                'error' => $e->getMessage(),
            ]);

            return $this->getPlaceholderInsights();
        }
    }

    /**
     * Gather context data for insight generation.
     */
    private function gatherInsightContext(int $workspaceId): array
    {
        // Recent post performance
        $recentPosts = Post::withoutGlobalScopes()
            ->where('workspace_id', $workspaceId)
            ->where('status', 'published')
            ->where('published_at', '>=', now()->subDays(7))
            ->count();

        $scheduledPosts = Post::withoutGlobalScopes()
            ->where('workspace_id', $workspaceId)
            ->where('status', 'scheduled')
            ->count();

        $draftPosts = Post::withoutGlobalScopes()
            ->where('workspace_id', $workspaceId)
            ->where('status', 'draft')
            ->count();

        // Recent analytics
        $latestSnapshot = AnalyticsSnapshot::withoutGlobalScopes()
            ->where('workspace_id', $workspaceId)
            ->orderByDesc('snapshot_date')
            ->first();

        $weekAgoSnapshot = AnalyticsSnapshot::withoutGlobalScopes()
            ->where('workspace_id', $workspaceId)
            ->where('snapshot_date', '<=', now()->subDays(7))
            ->orderByDesc('snapshot_date')
            ->first();

        return [
            'recent_published' => $recentPosts,
            'scheduled_count' => $scheduledPosts,
            'draft_count' => $draftPosts,
            'latest_followers' => $latestSnapshot?->followers_count ?? 0,
            'latest_impressions' => $latestSnapshot?->impressions ?? 0,
            'latest_engagement_rate' => $latestSnapshot?->engagement_rate ?? 0,
            'week_ago_followers' => $weekAgoSnapshot?->followers_count ?? 0,
            'week_ago_impressions' => $weekAgoSnapshot?->impressions ?? 0,
            'week_ago_engagement_rate' => $weekAgoSnapshot?->engagement_rate ?? 0,
        ];
    }

    private function buildInsightPrompt(array $data): string
    {
        $followerGrowth = $data['latest_followers'] - $data['week_ago_followers'];
        $impressionChange = $data['week_ago_impressions'] > 0
            ? round(($data['latest_impressions'] - $data['week_ago_impressions']) / $data['week_ago_impressions'] * 100, 1)
            : 0;

        return <<<PROMPT
        Berdasarkan data performa akun Threads dalam 7 hari terakhir:
        - Post yang dipublish: {$data['recent_published']}
        - Post terjadwal: {$data['scheduled_count']}
        - Post draft: {$data['draft_count']}
        - Followers saat ini: {$data['latest_followers']} (pertumbuhan: {$followerGrowth})
        - Impressions terakhir: {$data['latest_impressions']} (perubahan: {$impressionChange}%)
        - Engagement rate: {$data['latest_engagement_rate']}%

        Berikan 3 insight singkat dalam bahasa Indonesia:
        1. Insight tentang performa posting (success/warning/info)
        2. Insight tentang rekomendasi konten atau waktu posting (info)
        3. Insight tentang area yang perlu diperbaiki (warning/info)

        Format output JSON array:
        [
            {"type": "success|info|warning", "icon": "trending-up|bulb|alert-triangle|clock", "title": "Judul singkat", "body": "Deskripsi 1-2 kalimat"},
            ...
        ]

        HANYA output JSON array, tanpa teks lain.
        PROMPT;
    }

    private function getSystemPrompt(): string
    {
        return 'Kamu adalah analis media sosial yang ahli di platform Threads (Meta). '
            . 'Berikan insight actionable dalam bahasa Indonesia yang singkat dan jelas. '
            . 'Selalu output dalam format JSON array yang valid.';
    }

    /**
     * Parse AI response into structured insights array.
     */
    private function parseInsightResponse(string $response): array
    {
        // Try to parse JSON
        $cleaned = trim($response);

        // Remove markdown code block if present
        if (str_starts_with($cleaned, '```')) {
            $cleaned = preg_replace('/^```(?:json)?\s*/', '', $cleaned);
            $cleaned = preg_replace('/\s*```$/', '', $cleaned);
        }

        $parsed = json_decode($cleaned, true);

        if (is_array($parsed) && count($parsed) > 0) {
            // Validate structure
            return array_map(fn ($item) => [
                'type' => $item['type'] ?? 'info',
                'icon' => $item['icon'] ?? 'bulb',
                'title' => $item['title'] ?? 'Insight',
                'body' => $item['body'] ?? '',
            ], array_slice($parsed, 0, 3));
        }

        // Fallback if AI response can't be parsed
        return $this->getPlaceholderInsights();
    }

    /**
     * Fallback insights when AI is unavailable or data is stale.
     */
    public function getPlaceholderInsights(): array
    {
        return [
            [
                'type' => 'success',
                'icon' => 'trending-up',
                'title' => 'Waktu Posting Optimal',
                'body' => 'Rekomendasi posting hari ini pada pukul 19:00 WIB untuk engagement maksimal.',
            ],
            [
                'type' => 'info',
                'icon' => 'bulb',
                'title' => 'Topik Trending',
                'body' => 'Audiens merespon positif konten edukasi seputar "AI Tools". Perbanyak pilar ini.',
            ],
            [
                'type' => 'warning',
                'icon' => 'alert-triangle',
                'title' => 'Penurunan Reach',
                'body' => 'Evaluasi hashtag dan waktu posting untuk meningkatkan jangkauan konten.',
            ],
        ];
    }
}
